# Target Keywords Configuration for POCT Group Ecosystem
# Broad, generic product-category terms for GeM tender tracking.
# No brand/model names used — only clinical/product-level terminology.

import re

_RAW_KEYWORDS = {
    "Q-Line": [
        "Hematology analyzer",
        "3 Part Hematology Analyzer",
        "5 Part Hematology Analyzer",
        "Hemoglobin Analyzer",
        "HbA1c HPLC",
        "Coagulation analyzer",
        "ESR analyzer",
        "Biochemistry analyzer",
        "Semi-Auto Biochemistry Analyzer",
        "Automated Clinical Chemistry Analyzer",
        "Fully Auto Chemistry Analyzer",
        "Electrolyte analyzer",
        "Urine analyzer",
        "Clinical chemistry reagents",
        "ELISA reader",
        "ELISA washer",
        "Rapid test kits",
        "HIV 1/2 Antibody Rapid Test Kit",
        "HIV Ag/Ab 4th Gen Rapid Test Kit",
        "HBsAg Rapid Test Kit",
        "HCV Antibody Rapid Test Kit",
        "Syphilis Antibody Rapid Test Kit",
        "Dengue NS1 Rapid Test Kit",
        "Dengue Combo Rapid Test Kit",
        "Malaria Rapid Test Kit",
        "Pregnancy Rapid Test Kit",
        "HIV Syphilis Duo Rapid Test Kit",
        "POC Hemoglobin analyzer",
        "Nucleic acid extraction system",
        "Automated nucleic acid extraction system",
        "Viral Transport Medium",
        "COVID-19 RT-PCR Kit",
        "Molecular diagnostic kits",
        "Viral collection and transport medium",
    ],
    "Heidelco": [
        "Ventilator",
        "ICU Ventilator",
        "Portable Ventilator",
        "Defibrillator",
        "Patient monitor",
        "Multipara Monitor",
        "ECG machine",
        "Anesthesia machine",
        "Cardiac marker analyzer",
        "Critical care equipment",
        "Nasal mask",
        "Full face mask",
        "CPAP",
        "Patient circuit",
        "Breathing circuit",
        "Testlung",
        "Silicone anesthesia mask",
        "Anaesthesia mask",
        "Catheter mount",
        "Rebreathing bag",
        "HME filter",
        "Mapleson circuit",
        "Adult brain circuit",
        "Jackson Rees circuit",
        "Magill circuit",
        "Oxygen mask",
        "Venturi mask",
        "Jet nebulizer set",
        "Nebulizer mask kit",
        "Nasal cannula",
        "Syringe pump",
        "Infusion pump",
        "High Flow Nasal Cannula",
    ],
    "POCT": [
        "Turnkey laboratory",
        "Telemedicine services",
        "ICU management services",
        "Health screening services",
        "AI health kiosk",
        "Medical equipment supply",
        "Diagnostic laboratory instruments",
        "Comprehensive lab setup",
        "Laboratory infrastructure",
        "Pulse Oximeter",
        "Digital BP Apparatus",
        "Glucometer",
        "Nebulizer",
        "Oxygen Concentrator",
        "Infrared Thermometer",
    ],
    "iQline": [
        "Laboratory Information Management System",
        "LIMS",
        "E-Prescription software",
        "Radiology Information Management System",
        "RIMS",
        "Medical University Management System",
        "MUMS",
        "Hospital Information Management System",
        "HIMS",
        "Enterprise Resource Planning",
        "Early Warning System",
        "PACS",
    ],
}

# Clean any lingering citation artifacts automatically
def _clean(keyword):
    return re.sub(r":contentReference\[.*?\]\{.*?\}", "", keyword).strip()

TARGET_KEYWORDS = {
    brand: [_clean(kw) for kw in kws]
    for brand, kws in _RAW_KEYWORDS.items()
}
